name: Job Management Application

on:
  push:
    branches: [main]

# WORKFLOWS (or JOBS)
jobs:
  build:
    # Github already has its extension
    runs-on: ubuntu-latest
    steps:
      # Use checkout to clone a repository
      - name: Checkout code
        # PS: Uses => only to execute an action
        uses: actions/checkout@v4
      # Setup Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      # Build the project
      - name: Build project
        # Generate .jar from application
        run: mvn clean install
      # Login Docker
      - name: Login Docker
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      # Build Docker Image
      - name: Build Docker image
        run: docker build -t alexandrecpedro/job_management .
      # Publish Docker image
      - name: Publish image
        run: docker push alexandrecpedro/job_management
  deploy:
    # Only executes if build ends successfully
    needs: build
    runs-on: self-hosted
    steps:
      # Get image from DockerHub
      - name: Pull image DockerHub
        run: docker pull alexandrecpedro/job_management:latest
      # Remove the existing conatiner
      - name: Remove container
        run: docker rm -f job_management
      # Create and Run the downloaded container
      - name: Run Docker container
        run: docker run -d -p 8080:8080 -e DATABASE_URL=${{secrets.DATABASE_URL}} -e DATABASE_USERNAME=${{secrets.DATABASE_USERNAME}} -e DATABASE_PASSWORD='${{secrets.DATABASE_PASSWORD}}' --name job_management alexandrecpedro/job_management:latest
